### ISSUE TITLE
Also run Ci tests on Windows and macOS

### ISSUE THREAD

**Issue by pombredanne** [eliben/pyelftools#139]
I am considering replacing libdwarf and objdump in https://github.com/nexB/scancode-toolkit and https://github.com/nexB/scancode-toolkit-contrib by pyelftools and since I support also these other OSes it would be great for me to have the test suite running there too.

**Comment by eliben** [comment]
Feel free to submit a PR. I'm not sure Travis supports this today

**Comment by pombredanne** [comment]
I will. One thing you can do is send an email to Travis to ask them to add support for maCOS? And when I will have the appveyor support in, you will also need to signup there an enable this repo. Would this is OK with you?

**Comment by eliben** [comment]
Actually, can I ask why you can just run the test suite of your tool/project on whatever OS you need?

The reason this may be problematic for pyelftools itself is that the majority of tests rely on a Linux-variant of `readelf`. I even carry a version-locked version of `readelf` in the repo for this reason, because between versions `readelf` tends to annoyingly change the structure of their output slightly. This would be problematic to setup as tests on Windows and OS X. Not impossible, but I think more trouble than it's worth.
