### ISSUE TITLE
section_in_segment() logic contradicts comment

### ISSUE THREAD

**Issue by jameshippisley** [eliben/pyelftools#263]
I don't really understand the elf internals, but I was having an issue with a section not showing up in my elffile, and I tracked it down to this section of code:

https://github.com/eliben/pyelftools/blob/a347dbfab622ab98d9747d862ade9e6b6fd9425c/elftools/elf/segments.py#L43-L47

Assuming the logic of the comment is correct, then I think it should be  "segtype **not** in ('PT_TLS', 'PT_GNU_RELR0', 'PT_LOAD')"

**Comment by rupran** [comment]
I think you are correct.

The logic in the referenced `elf/include/internal.h` file from binutils has the following code inside the `ELF_SECTION_IN_SEGMENT_1` macro:

```C
    ((((sec_hdr)->sh_flags & SHF_TLS) != 0)				\
     && ((segment)->p_type == PT_TLS					\
	 || (segment)->p_type == PT_GNU_RELRO				\
	 || (segment)->p_type == PT_LOAD))				\
```

so in this case the binutils continues with the evaluation below.

What's even worse is that the name of the segment should be `PT_GNU_RELRO` instead of `PT_GNU_RELR0`. I'll try to rewrite the check (and the one below) and fix this up.
