### ISSUE TITLE
Suggestion: try and obtain "elftools" PyPI package name

### ISSUE THREAD

**Issue by Gadgetoid** [eliben/pyelftools#334]
Thanks for building and maintaining this- it's given us the tooling to do relocations on ARM binaries so they can be run from arbitrary locations in external flash.

I keep trying to `pip install elftools` and getting the wrong package. I realise that's on me but it looks like https://pypi.org/project/elftools/ might be abandoned- it links to a deleted (or made private?) GitHub repository and has only one alpha release in August 2018.

It could be worth reaching out to @jme2041 to ask nicely whether they would consider handing over the name. I've had some success doing this before with Python projects and don't mind doing the legwork.

**Comment by eliben** [comment]
Can two pip packages point to the same thing? It's clear that `pyelftools` has to keep working for everyone.

It's not clear to me that this makes sense unless the `elftools` you point to has ~0 users.

**Comment by Gadgetoid** [comment]
You can use a stub package that depends on `pyelftools`, or deploy the same package twice to the two locations.

Of course whether this is worthwhile is *entirely* a matter of opinion and it's not clear the benefits (a cleaner package name that corresponds to the installed module) outweigh the drawbacks (more maintenance burden).

I deeply suspect `elftools` is abandoned and has no users- the strongest indicator of this is that the package doesn't do anything. It's just empty source files and stubbed out code.

**Comment by Gadgetoid** [comment]
@jme2041 genuinely didn't expect a response here- thank you for taking the time to reply!

Assuming they are happy with the legwork required to get a stub package uploaded... I guess it's over to @eliben now.

I sort-of...  barged in here out of the blue because I kept accidentally running `pip install elftools` and getting the wrong package 😆 (a problem, I'll admit, that's only a problem when I don't read the manual)

**Comment by eliben** [comment]
@Gadgetoid I believe having a stub package or a duplicate package just to prevent a `pip` typo is a bit too much effort, to be honest.

One easier approach may be to just cause `pip install elftools` to fail somehow, and add a doc page pointing to `pyelftools` instead. Since @jme2041 is willing to hand over the name, perhaps this could be arranged - but I'll have to dig in the settings of PyPI to see how.

@jme2041 thanks for your responsiveness. If you feel you don't need the package name `elftools` any more, please transfer it to my ownership -- https://pypi.org/user/eliben/
