### ISSUE TITLE
Not all symbols are reachable via`Dynamic.get_symbol`

### ISSUE THREAD

**Issue by danzat** [eliben/pyelftools#342]
It looks like `Dynamic.get_symbol` attempts to guess the number of symbols in the binary (via some heuristic), then creates a list of all the symbols and retrieves the requested one.

This can be somewhat problematic is some ELF as can be seen in the attached [sample.zip](https://github.com/eliben/pyelftools/files/5542539/sample.zip)
:

```python
with open("sample", "rb") as elf_stream:
    elf = ELFFile(elf_stream)
    dynamic = find_segment(elf, "PT_DYNAMIC")
    for _, rel_table in dynamic.get_relocation_tables().items():
        for rel in rel_table.iter_relocations():
            symbol_index = rel["r_info_sym"]
            if symbol_index:
                try:
                    print("Reloc@0x{:x}={}".format(
                        rel["r_offset"],
                        dynamic.get_symbol(symbol_index).name))
                except IndexError:
                    print("Can't find symbol for reloc@0x{:x}(index={})".format(
                        rel["r_offset"],
                        symbol_index))
```

As you can see, the symbols specified in the relocation entries can not be reached. A loader would not run into such a problem as it does not "know" the number of symbols, it just trusts the relocation table to contain the correct symbol indices and just accesses them as if the symbol table is an unbound array.

This is just to show that there's nothing wrong with the ELF in question. It loads and runs correctly. The fact that it has an empty symbol hash table (the reason for the faulty symbol count guess) won't stop it from functioning.

We can solve this by providing an "unrestricted" symbol resolution method to `Dynamic`:

```python
class Dynamic:
    # ...
    def get_symbol_unrestricted(self, index):
        _, tab_offset = self.get_table_offset("DT_SYMTAB")

        symbol_size = self.elfstructs.Elf_Sym.sizeof()

        string_table = self._get_stringtable()

        symbol = struct_parse(
                self.elfstructs.Elf_Sym,
                self._stream,
                index * symbol_size + tab_offset,
                )

        symbol_name = string_table.get_string(symbol["st_name"])

        return Symbol(symbol, symbol_name)
```

Thanks

**Comment by rupran** [comment]
Looks like I changed that behaviour by introducing the `.gnu.hash` and `.hash` logic in 27941c50fef8cff8ef991419511664154c8cdf52. Before that change, it used a value determined by some crude pointer comparisons in the dynamic segment which easily failed for shared objects. 

Do you know why there is a hash section in the sample file but it does not contain sensible values? Is that common on architectures other than x86?

In general, I think having the opportunity to (more or less) fully support dealing with such cases as a loader does would be nice (that is, relying on the smallest set of information required by the ELF spec), although the particular behaviour might again be implementation-defined (differences between musl and glibc, for example).

**Comment by rupran** [comment]
So, looking at the corresponding code in `SymbolTableSection`, the `get_symbol()` method there does not do any checks on the given index (see below). I would argue that we could do the same in `DynamicSegment.get_symbol()` instead of relying on the heuristics from `iter_symbols()`, so basically we could replace the current implementation with your suggested code (and use this new implementation from `iter_symbols()` to avoid redundancy).

The other methods probably should still stay as they are, there is no easy way to determine the actual number of symbols in this case. This again makes it hard to iterate over all symbols and construct a number-to-name mapping for `get_symbol_by_name`... but those are all "convenience methods" and not strictly required by a loader.

What do you think?

Implementation of `get_symbol()` in `SymbolTableSection`:
https://github.com/eliben/pyelftools/blob/9f851f7b6979d5dc3e848c553161913502f11b83/elftools/elf/sections.py#L185-L196
