### ISSUE TITLE
Calculating framebase location offsets

### ISSUE THREAD

**Issue by vsoch** [eliben/pyelftools#359]
Hi! I was planning on using `DW_AT_location` to get metadata about locations, but it's not quite what I want - I'm looking for a number relative to the framebase on the stack, e.g., `framebase+16`, where frame base is the base address of a function's call stack frame. Is this something that pyelftools could help to calculate? i was looking at `LocationEntry` and noticed that there are references to a base, and several offsets.

https://github.com/eliben/pyelftools/blob/master/elftools/dwarf/locationlists.py

Any help that you could provide would be greatly appreciated!

**Comment by sevaa** [comment]
Local variables and parameters are not always stored in a memory location relative to the framebase. Sometimes it's a register. Sometimes it's a memory location relative to an arbitrary register. Sometimes the compiler stores not the variable itself, but some expression with it.

That's where DWARF expressions come in. In order to write the logic of variable value recovery, you need to put together a DWARF expression interpreter. `pyelftools` will let you parse the expressions, but it doesn't have the interpreter. Expressions are stored in location lists.

`framebase+offset` is one particular DWARF expression. But not the only possible one.

Now, depending on the particulars your project, you may not have to implement the whole gamut of DWARF opcodes. In my experience with Android binaries from a single codebase, written in pretty vanilla C++, a handful of opcodes is all you ever encounter.

**Comment by vsoch** [comment]
Thank you!
