### ISSUE TITLE
How to get DW_OP_addr from DW_FORM_sec_offset

### ISSUE THREAD

**Issue by Samuel-Fipps** [eliben/pyelftools#453]
I have script I have been using for a long time, but now it's getting DW_FORM_sec_offset's. It was only made for DW_FORM_exprloc.

Before I got the DW_OP_addr: by doing
`DWDESC.describe_DWARF_expr(die.attributes['DW_AT_location'].value, die.cu.structs)`

This doesn't work with DW_FORM_sec_offset though. 
I get this error:
`return b''.join(bytes((b,)) for b in bytelist)
TypeError: 'int' object is not iterable
`
Which is expected since the format is differen't.

**Comment by Samuel-Fipps** [comment]
If I set debugger optimization's to zero I don't get the DW_FORM_sec_offset's is there anyway to include these?

**Comment by sevaa** [comment]
I presume `describe_DWARF_expr` is *your* script. I don't know how does it work, and therefore can't debug it for you. In general, pyelftools has a general purpose location list parser - method `parse_from_attribute` in class `LocationParser`.

One thing you might be missing, a variable may have *several* locations depending on where in the code you are. Was your code written with location lists in mind? It doesn't seem that way. DWARF accommodates that by having a "location list" - that's a collection of IP range to DWARF expression mappings. In order to know the location of a variable in this scenario, you need to know the position in code where you are.

Yet another thing of note, not all DWARF locations have the form of a single DW_OP_addr. A variable may be, say, in a register.

**Comment by sevaa** [comment]
@Samuel-Fipps Is this still an issue?

**Comment by Samuel-Fipps** [comment]
I figured out it's not easy to get the value of a variable when you compile optimized flag. That's what was wrong. Thanks!
