### ISSUE TITLE
How to tell if a CU is 64 bit?

### ISSUE THREAD

**Issue by wqferr** [eliben/pyelftools#585]
The dwarfdump.py example file has a line containing cu.is64 but it doesn't seem to exist anymore.

**Comment by sevaa** [comment]
The `is64` property is checked, if you look carefully, on the objects that are enumerated by `ranges_sec.iter_CUs()`. Those are not `CompileUnit` objects.

To check the target bitness of a `CompileUnit`, check `cu_header.address_size`. It will be 4 or 8. That said, on the majority of platforms bitness does not vary between CUs within a binary; you can check it from the file header or from the `DWARFInfo` header. For the latter, check `config.default_address_size` on `DWARFInfo`.

**Comment by wqferr** [comment]
Thank you!

**Comment by sevaa** [comment]
@wqferr: On a second thought. Were you asking about the size of the *debuggee program addresses*, or about the *bitness of DWARF itself*? Since v3, the size of internal offsets in DWARF itself doesn't have to match the size of addresses used by the target CPU. I assumed you were asking about the CPU. If you were interested in DWARF bitness, use `dwarf_format()` on the `CompileUnit` object. That would return either 32 or 64.

**Comment by wqferr** [comment]
Turns out, you're right! Or at least your question lead me to the right path. I didn't know this was an option and, after checking the documentation for the tool I'm contributing to, this is indeed what I wanted.

Thanks again!
